name: microservices-demo
services:
    emailservice-emailservice:
        annotations:
            compose.score.dev/workload-name: emailservice
        build:
            context: src/emailservice/
        environment:
            DISABLE_PROFILER: "1"
            PORT: "8080"
        hostname: emailservice
