name: microservices-demo
services:
    cartservice-cartservice:
        annotations:
            compose.score.dev/workload-name: cartservice
        build:
            context: src/cartservice/src/
        depends_on:
            wait-for-resources:
                condition: service_completed_successfully
                required: true
        environment:
            REDIS_ADDR: redis-JHNLhk:6379,user=default,password=nLxdnOMvmqtOKjVS
        hostname: cartservice
    emailservice-emailservice:
        annotations:
            compose.score.dev/workload-name: emailservice
        build:
            context: src/emailservice/
        depends_on:
            wait-for-resources:
                condition: service_completed_successfully
                required: true
        environment:
            DISABLE_PROFILER: "1"
            PORT: "8080"
        hostname: emailservice
    redis-JHNLhk:
        command:
            - /usr/local/etc/redis/redis.conf
        entrypoint:
            - redis-server
        image: redis:7-alpine
        labels:
            dev.score.compose.res.uid: redis.default#cartservice.redis-cart
        restart: always
        volumes:
            - type: bind
              source: .score-compose/mounts/redis-JHNLhk/redis.conf
              target: /usr/local/etc/redis/redis.conf
              read_only: true
            - type: volume
              source: redis-JHNLhk-data
              target: /data
              volume:
                nocopy: true
    wait-for-resources:
        command:
            - echo
        depends_on:
            redis-JHNLhk:
                condition: service_started
                required: true
        image: alpine
volumes:
    redis-JHNLhk-data:
        name: redis-JHNLhk-data
        driver: local
        labels:
            dev.score.compose.res.uid: redis.default#cartservice.redis-cart
